/* =========================================================
   PROJECTS
   Full register — ordered by display number.
   The first 5 entries include homeSummary / homeTags for the
   homepage "Selected work" section.
   ========================================================= */

export interface Tag {
  label: string;
  isLive?: boolean;
}

export interface Project {
  num: string;
  title: string;
  /** Secondary label shown in muted style, e.g. "(Jankenpon)" */
  subtitle?: string;
  /** Full description used on the /work page. */
  desc: string;
  /** Full tag list used on the /work page. */
  tags: Tag[];
  href: string;
  /** Shorter description shown in the homepage "Selected work" strip. */
  homeSummary?: string;
  /** Curated tag subset shown on the homepage strip. */
  homeTags?: Tag[];
}

export const projects: Project[] = [
  {
    num: '01',
    title: 'Doodle Duel',
    subtitle: '(Jankenpon)',
    desc: 'A real‑time competitive web party game where a vision‑LLM acts as referee on a shared canvas. Players draw objects under a time limit; the Gemini API classifies drawings and determines which object wins. An enhanced drawing is generated by ImageGen 4 for added fun.',
    tags: [
      { label: '● Live', isLive: true },
      { label: 'React' },
      { label: 'TypeScript' },
      { label: 'Vite' },
      { label: 'Tailwind CSS' },
      { label: 'Node.js' },
      { label: 'Express' },
      { label: 'Socket.IO' },
      { label: 'Gemini API' },
      { label: 'Docker' },
      { label: 'Traefik' },
    ],
    href: 'https://github.com/heyGio/jankenpon/tree/loc/hehe',
    homeSummary: 'A real‑time competitive web party game where a vision‑LLM acts as referee on a shared canvas.',
    homeTags: [
      { label: '● Live', isLive: true },
      { label: 'React' },
      { label: 'Gemini API' },
      { label: 'Socket.IO' },
    ],
  },
  {
    num: '02',
    title: 'ArcanaAI',
    desc: 'AI‑powered tarot reading service using OpenAI function calling, real‑time chat, multiple decks, dual payment (Lemon Squeezy & MetaMask), Cloudflare R2 asset storage, and WebSocket notifications. Containerised with Docker and CI/CD via GitHub Actions.',
    tags: [
      { label: '● Live', isLive: true },
      { label: 'OpenAI' },
      { label: 'FastAPI' },
      { label: 'SQLAlchemy' },
      { label: 'PostgreSQL' },
      { label: 'Redis' },
      { label: 'Celery' },
      { label: 'Next.js' },
      { label: 'TypeScript' },
      { label: 'Cloudflare R2' },
      { label: 'Docker' },
    ],
    href: 'https://github.com/vanloc1808/arcana-ai',
    homeSummary: 'AI‑powered tarot reading service — OpenAI function‑calling, VertexAI, persistent state with PostgreSQL & Redis, and a deliberately mystical UI.',
    homeTags: [
      { label: '● Live', isLive: true },
      { label: 'Next.js' },
      { label: 'OpenAI' },
      { label: 'VertexAI' },
      { label: 'Redis' },
      { label: 'Supabase' },
    ],
  },
  {
    num: '03',
    title: 'Fake News Analysis & Detection',
    desc: 'End‑to‑end neural networks for cheapfake detection (manipulated images/videos), online reputation verification, and real‑time authenticity guidance. Features credibility scoring algorithms and a Streamlit interface. Undergraduate thesis project.',
    tags: [
      { label: 'Python' },
      { label: 'PyTorch' },
      { label: 'Streamlit' },
      { label: 'Selenium' },
      { label: 'Docker' },
    ],
    href: 'https://github.com/nbtin/fakenews-detection-demo',
    homeSummary: 'End‑to‑end neural networks for cheapfake detection, paired with online reputation checking and real‑time authenticity guidance. Undergraduate thesis project.',
    homeTags: [
      { label: 'PyTorch' },
      { label: 'Streamlit' },
      { label: 'Docker' },
    ],
  },
  {
    num: '04',
    title: 'Connect',
    desc: 'Feature‑rich chat application (real‑time messaging, group chat, file sharing) built for the Software Architecture course. ReactJS frontend + Django REST Framework backend, PostgreSQL, Supabase, CI/CD with Docker, Jenkins, and GitHub Actions.',
    tags: [
      { label: 'ReactJS' },
      { label: 'Django REST Framework' },
      { label: 'PostgreSQL' },
      { label: 'Supabase' },
      { label: 'Docker' },
      { label: 'Jenkins' },
    ],
    href: 'https://github.com/software-architecture-20tn/chat-app-frontend',
    homeSummary: 'Feature‑rich real‑time chat app — group chat, file sharing, and a full CI/CD pipeline — built for the Software Architecture course.',
    homeTags: [
      { label: 'ReactJS' },
      { label: 'Django REST Framework' },
      { label: 'PostgreSQL' },
    ],
  },
  {
    num: '05',
    title: 'MiniShopping',
    desc: 'E‑commerce mobile app (Android) with user authentication, product catalogue, cart management, order processing, and payment integration. Django REST Framework backend with NoSQL database. Mobile Development course project.',
    tags: [
      { label: 'Android' },
      { label: 'Django REST Framework' },
      { label: 'NoSQL' },
    ],
    href: 'https://github.com/mekanican/MiniShopping',
    homeSummary: 'E‑commerce Android app with catalogue, cart, order processing, and payment integration on a Django REST Framework backend.',
    homeTags: [
      { label: 'Android' },
      { label: 'Django REST Framework' },
      { label: 'NoSQL' },
    ],
  },
  {
    num: '06',
    title: 'PC Control via Email',
    desc: 'Remote computer control via specially formatted emails. Custom email protocol handler processes commands for system operations, file management, and monitoring tasks. Built with Python socket programming for the Computer Network course.',
    tags: [
      { label: 'Python' },
      { label: 'Socket' },
    ],
    href: 'https://github.com/vanloc1808/computer-network-projects/tree/main/socket_email',
  },
  {
    num: '07',
    title: 'Chess Game',
    desc: 'Full chess engine with standard rules, move validation, graphical two‑player gameplay, complete move history, and intelligent move suggestions. Built entirely in C++ for the OOP course, demonstrating inheritance, polymorphism, and encapsulation.',
    tags: [
      { label: 'C++' },
    ],
    href: 'https://github.com/vanloc1808/chess-game',
  },
  {
    num: '08',
    title: 'Search Engine',
    desc: 'High‑performance text search engine with efficient string matching algorithms, data indexing, fuzzy search, and result ranking. Processes large datasets of text files with fast query response. Arts of Programming course project.',
    tags: [
      { label: 'C++' },
    ],
    href: 'https://github.com/vanloc1808/search-engine',
  },
  {
    num: '09',
    title: 'Big Integers',
    desc: 'Arbitrary‑precision arithmetic library implementing addition, subtraction, multiplication, division, and logical operations on unbounded integers. Demonstrates algorithm optimisation, memory management, and number theory concepts in C++.',
    tags: [
      { label: 'C++' },
    ],
    href: 'https://github.com/mekanican/BigInteger',
  },
];

/** The first N projects shown on the homepage "Selected work" strip. */
export const FEATURED_PROJECT_COUNT = 5;
